name: Batch Test

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    name: A Job to batch
    steps:
      - uses: actions/checkout@v4
      - name: Batch Test
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
      - run: echo $(npm -v)
      - run: echo $(node -v)
      - run: echo wow


